# The machine constraints for each service in this bundle
# have been commented out so you don't run into quota
# problems on public clouds. Modify and uncomment the
# constraints: lines for each service to reflect your
# deployment before moving to production.
#
series: xenial
services:
  "kubernetes-master":
    charm: /home/ubuntu/builds/kubernetes-master
    series: xenial
    num_units: 1
    annotations:
      "gui-x": "800"
      "gui-y": "850"
  flannel:
    charm: /home/ubuntu/builds/flannel
    series: xenial
    annotations:
      "gui-x": "500"
      "gui-y": "750"
  "kubeapi-load-balancer":
    charm: /home/ubuntu/builds/kubeapi-load-balancer
    series: xenial
    num_units: 1
    expose: true
    annotations:
      "gui-x": "450"
      "gui-y": "250"
  easyrsa:
    charm: /home/ubuntu/builds/easyrsa
    num_units: 1
    series: xenial
    annotations:
      "gui-x": "450"
      "gui-y": "550"
  "kubernetes-worker":
    charm: /home/ubuntu/builds/kubernetes-worker
    num_units: 2
    series: xenial
    annotations:
      "gui-x": "100"
      "gui-y": "850"
  etcd:
    charm: /home/ubuntu/builds/etcd
    series: xenial
    num_units: 3
    annotations:
      "gui-x": "800"
      "gui-y": "550"
relations:
  - - "kubernetes-master:kube-api-endpoint"
    - "kubeapi-load-balancer:apiserver"
  - - "kubernetes-master:loadbalancer"
    - "kubeapi-load-balancer:loadbalancer"
  - - "kubernetes-master:cluster-dns"
    - "kubernetes-worker:kube-dns"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "kubernetes-master:sdn-plugin"
    - "flannel:host"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "kubernetes-worker:sdn-plugin"
    - "flannel:host"
  - - "kubernetes-worker:kube-api-endpoint"
    - "kubeapi-load-balancer:website"
  - - "flannel:etcd"
    - "etcd:db"
  - - "kubeapi-load-balancer:certificates"
    - "easyrsa:client"
